version: '3'
services: 
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    deploy:
      mode: replicated
      replicas: 1
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=postgres
    volumes:
      - ./db-data/postgres:/var/lib/postgresql/data